### ISSUE TITLE
Hello，你好，请问用这个能解析群的记录吗？

### ISSUE THREAD

**Issue by yinsHub** [libra146/wechat_analysis#1]
聊天记录生成方式如下：
![image](https://user-images.githubusercontent.com/80821358/120997219-98b7ed80-c7b9-11eb-809d-4cef1eb879f6.png)
![image](https://user-images.githubusercontent.com/80821358/120997263-a1102880-c7b9-11eb-8d83-9aa35f2481fc.png)

**Comment by libra146** [comment]
抱歉，这个不可以，我这个是用来解析·解密并分析手机版微信的聊天记录的。

**Comment by yinsHub** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
